kitty:
  idempontent:
    firstLevelType:
    secondLevelType:

spring:
  datasource:
    url: jdbc:mysql://192.168.10.225:3306
    username: ld225_rw
    password: laidian225
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 192.168.22.33
#    port: 6222
#    password: root

